# Generated by Django 6.1 on 2026-08-19 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("analyzer", "0015_knowndevice"),
        ("analyzer", "0015_resumeanalysis_experience_level"),
    ]

    operations = []
