# Generated by Django 6.1 on 2026-08-19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analyzer", "0015_knowndevice"),
        ("analyzer", "0015_resumeanalysis_experience_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="resumeanalysis",
            name="partial_skills",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
